# Generated by Django 6.0 on 2025-12-28 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_category",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consultant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("middle_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("telegaram_nickname", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_of_specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="consultant_menu.category",
                    ),
                ),
            ],
            options={
                "db_table": "consultants",
            },
        ),
    ]
