# Generated by Django 6.0 on 2025-12-28 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_menu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("number", models.IntegerField()),
                ("telegram_nickname", models.CharField(blank=True, max_length=255)),
                (
                    "who_your_consultant_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="consultant_menu.consultant",
                    ),
                ),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.AddField(
            model_name="consultant",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="consultant_menu.clients",
            ),
        ),
    ]
