# Generated by Django 6.0 on 2025-12-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_menu", "0002_clients_consultant_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consultant",
            old_name="telegaram_nickname",
            new_name="telegram_nickname",
        ),
    ]
