# Generated by Django 6.0 on 2026-01-02 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultant_menu",
            "0003_rename_telegaram_nickname_consultant_telegram_nickname",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
