# Generated by Django 6.0 on 2026-01-03 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_menu", "0005_calendar_service_timeslot_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="consultant_menu.calendar",
            ),
        ),
    ]
