# Generated by Django 6.0 on 2026-01-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_menu", "0006_service_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_end_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время окончания записи"
            ),
        ),
    ]
