# Generated by Django 6.0 on 2026-01-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_menu", "0007_booking_booking_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="profile_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание профиля"
            ),
        ),
        migrations.AddField(
            model_name="consultant",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="consultant_photos/",
                verbose_name="Фото специалиста/организации",
            ),
        ),
        migrations.AddField(
            model_name="consultant",
            name="social_facebook",
            field=models.URLField(blank=True, null=True, verbose_name="Facebook"),
        ),
        migrations.AddField(
            model_name="consultant",
            name="social_instagram",
            field=models.URLField(blank=True, null=True, verbose_name="Instagram"),
        ),
        migrations.AddField(
            model_name="consultant",
            name="social_telegram",
            field=models.URLField(blank=True, null=True, verbose_name="Telegram"),
        ),
        migrations.AddField(
            model_name="consultant",
            name="social_vk",
            field=models.URLField(blank=True, null=True, verbose_name="VK"),
        ),
        migrations.AddField(
            model_name="consultant",
            name="social_youtube",
            field=models.URLField(blank=True, null=True, verbose_name="YouTube"),
        ),
        migrations.AddField(
            model_name="consultant",
            name="video_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на видео"
            ),
        ),
        migrations.AddField(
            model_name="consultant",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Веб-сайт"),
        ),
    ]
