# Generated by Django 6.0 on 2026-01-17 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_menu", "0008_consultant_profile_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="client_telegram",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Telegram клиента"
            ),
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_calendar_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Google Calendar включен"
                    ),
                ),
                (
                    "google_calendar_connected",
                    models.BooleanField(
                        default=False, verbose_name="Google Calendar подключен"
                    ),
                ),
                (
                    "google_calendar_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID календаря Google",
                    ),
                ),
                (
                    "telegram_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Telegram уведомления включены"
                    ),
                ),
                (
                    "telegram_connected",
                    models.BooleanField(
                        default=False, verbose_name="Telegram подключен"
                    ),
                ),
                (
                    "telegram_bot_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Токен бота Telegram",
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Chat ID Telegram",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration",
                        to="consultant_menu.consultant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Интеграция",
                "verbose_name_plural": "Интеграции",
                "db_table": "integrations",
            },
        ),
    ]
