# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_menu", "0009_booking_client_telegram_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="google_refresh_token",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Google refresh token",
            ),
        ),
    ]
