"""
Django settings for appoinment_sistem project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Загружаем переменные окружения из .env файла
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-f29bdmik6$bq4-y&%u$ht7k$4kb=-fkuz(+ct$gpy)+4zh*aua')

# SECURITY WARNING: don't run with debug turned on in production!
# По умолчанию DEBUG=True для удобства разработки, в продакшене установите DEBUG=False через переменную окружения
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Парсим ALLOWED_HOSTS, убирая пробелы
# Если DEBUG=True, Django автоматически разрешит localhost, поэтому для разработки можно оставить пустым
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']  # Для разработки разрешаем все хосты
else:
    ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '').split(',') if host.strip()] if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "consultant_menu.apps.ConsultantMenuConfig",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Для статических файлов в продакшене
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "appoinment_sistem.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "appoinment_sistem.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# MySQL на хостинге (reg.ru и др.), SQLite для локальной разработки
if os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'appointment_db'),
            'USER': os.getenv('DB_USER', 'appointment_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'db'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "consultant_menu" / "static",
]

# WhiteNoise для статических файлов в продакшене
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Настройки для медиа файлов (загружаемые пользователями)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Добавьте в конец файла:

# Настройки для Django REST Framework
REST_FRAMEWORK = {
    # Используем Session Authentication - это встроено в Django
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # Авторизация через сессию (cookie)
    ],
    # По умолчанию API требуют авторизацию (можно отключить в конкретных views)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Только авторизованные пользователи
    ],
}

# Безопасность для продакшена
if not DEBUG:
    # Проверяем, используется ли HTTPS через переменную окружения
    USE_HTTPS = os.getenv('USE_HTTPS', 'False') == 'True'
    
    if USE_HTTPS:
        # HTTPS настройки
        # SECURE_SSL_REDIRECT отключен, т.к. редирект делает nginx
        SECURE_SSL_REDIRECT = False  # Nginx делает редирект 301
        SESSION_COOKIE_SECURE = True  # Cookies только через HTTPS
        CSRF_COOKIE_SECURE = True  # CSRF cookies только через HTTPS
        # HSTS отключен для самоподписанного сертификата (включите с Let's Encrypt)
        SECURE_HSTS_SECONDS = 0  # Отключено для самоподписанного сертификата
        SECURE_HSTS_INCLUDE_SUBDOMAINS = False
        SECURE_HSTS_PRELOAD = False
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Для работы за nginx
    else:
        # HTTP настройки (для разработки или до настройки SSL)
        SECURE_SSL_REDIRECT = False
        SESSION_COOKIE_SECURE = False
        CSRF_COOKIE_SECURE = False
    
    # Общие настройки безопасности
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'