# Generated by Django 4.2.7 on 2025-11-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "last_name_2",
                    models.CharField(max_length=50, verbose_name="Отчетсво"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "specializations",
                    models.CharField(max_length=50, verbose_name="Специализация"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_sector",
                    models.CharField(max_length=50, verbose_name="Сфера услуг"),
                ),
            ],
        ),
    ]
